# Metadata
spring.application.name=notification-service
server.port=8083

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service URLs
user.service.url=http://localhost:8081
booking.service.url=http://localhost:8082
appointment.service.url=http://localhost:8084
