services:
  mongodb:
    image: mongo:latest
    container_name: appointment-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - appointment-network


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appointment-network

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - appointment-network

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - appointment-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - appointment-network
    depends_on:
      - eureka-server
      - user-service
      - booking-service
      - notification-service

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/userdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - appointment-network
    depends_on:
      - mongodb
      - eureka-server

  doctor-service:
    build:
      context: .
      dockerfile: doctor-service/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/userdb
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - appointment-network
    depends_on:
      - mongodb
      - eureka-server

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - appointment-network
    depends_on:
      - mongodb
      - eureka-server

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/userdb
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - appointment-network
    depends_on:
      - eureka-server
      - rabbitmq
      - mongodb

networks:
  appointment-network:
    driver: bridge

volumes:
  mongo-data:
