spring.application.name=booking-service

# Server Port
server.port=8083

# MongoDB Atlas Connection
spring.data.mongodb.uri=${MONGO_URI}

# Other Microservice URLs
auth.service.url=http://localhost:8081
slot.service.url=http://localhost:8082
notification.service.url=http://localhost:8084