spring.application.name=booking-service
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/bookingdb

logging.level.root=INFO
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.com.ctse.booking_service=DEBUG