<<<<<<< HEAD:doctor-schedule-service/src/main/resources/application.properties
spring.application.name=doctor-schedule-service
server.port=8082

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/doctor-schedule-db

# Logging
logging.level.root=INFO
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.com.ctse.booking_service=DEBUG
=======
# Metadata
spring.application.name=booking-service
server.port=8082

# Database
spring.data.mongodb.uri=mongodb://localhost:27017/bookingdb

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
>>>>>>> feature/api-gateway:booking-service/src/main/resources/application.properties

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service URLs
user.service.url=http://localhost:8081
notification.service.url=http://localhost:8083
appointment.service.url=http://localhost:8084
