spring.application.name=doctore-schedule-service
server.port=8082

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/doctor-schedule-db

logging.level.root=INFO
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.com.ctse.booking_service=DEBUG

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always