# Database Override
spring.data.mongodb.uri=mongodb://mongodb:27017/bookingdb

# Service URL Overrides
user.service.url=http://user-service:8081
notification.service.url=http://notification-service:8083
appointment.service.url=http://appointment-service:8084