# Metadata
spring.application.name=booking-service
server.port=8082

# Database
spring.data.mongodb.uri=mongodb://localhost:27017/bookingdb

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service URLs
user.service.url=http://localhost:8081
notification.service.url=http://localhost:8083
appointment.service.url=http://localhost:8084
