# Metadata
spring.application.name=appointment-service
server.port=8084

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service URLs
user.service.url=http://localhost:8081
booking.service.url=http://localhost:8082
notification.service.url=http://localhost:8083