name: API Gateway CI/CD

on:
  push:
    branches: [ "main", "master", "dev", "feature/**" ]
    paths:
      - 'api-gateway/**'
      - 'pom.xml'
  pull_request:
    branches: [ "main", "master", "dev" ]
    paths:
      - 'api-gateway/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make Maven Wrapper Executable
      run: chmod +x mvnw

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests -pl api-gateway -am

    - name: SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests -Dsonar.projectKey=${{ github.repository }} -pl api-gateway -am

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/api-gateway:${{ github.sha }} -f api-gateway/Dockerfile .
        docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/api-gateway:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp up --name api-gateway --resource-group AppointmentApp-RG --environment AppointmentEnv --image ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/api-gateway:${{ github.sha }} --registry-server ${{ secrets.REGISTRY_USERNAME }}.azurecr.io --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --ingress external --target-port 8080
